### ISSUE TITLE
Nested Ternaries and Object Properties

### ISSUE THREAD

**Issue by khanhtranngoccva** [bob-fornal/better-practices#1]
### Idea: avoid using nested ternary operators. 
In a nutshell: many newbies try to write very short solutions to impress people, but in the end, no one will like them because they're so hard to read and maintain.

### Idea 2: use dot notations for fixed properties and square brackets for dynamic properties or properties of data objects fetched from an API.
Context: from my own experience, this can be done to avoid autocompletion issues in IDEs.

**Comment by bob-fornal** [comment]
I'll work on getting both of these in this weekend under JavaScript.

Issue 1: I see examples where the nested ternary are converted to if-branch, case statements, or using JSON objects for clarity and simplification.

Issue 2: I like this one. Some simple examples will suffice.
